/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

uint8_t numero_1 = 0;
uint8_t numero_2 = 0;
uint8_t numero_3 = 0;
uint8_t numero_4 = 0;
uint8_t resultado_1 = 0;
uint8_t resultado_2= 0;

void suma(void);

int main(void)
{
	suma();
	numero_1 =15;
	numero_2=30;

	suma();

	return 0;
}
void suma(void){
	resultado_1 = numero_1 + numero_2;

}
